//addSbtPlugin("com.disneystreaming.smithy4s" % "smithy4s-sbt-codegen" % "0.18.3")
addSbtPlugin("org.scala-js"                 % "sbt-scalajs"          % "1.14.0")
addSbtPlugin("org.scalameta"                % "sbt-scalafmt"         % "2.5.2")
addSbtPlugin("org.typelevel"                % "sbt-tpolecat"         % "0.5.0")
addSbtPlugin("org.scalablytyped.converter"  % "sbt-converter"        % "1.0.0-beta43")
addSbtPlugin("com.eed3si9n"                 % "sbt-buildinfo"        % "0.11.0")
